# Generated by Django 5.2.4 on 2025-07-16 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_file', models.FileField(help_text='Upload video file (mp4, mov, avi, mkv)', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload thumbnail image (optional)', null=True, upload_to='thumbnails/')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('tags', models.CharField(help_text="Comma-separated tags (e.g., 'Premiere Pro, After Effects, Color Grading')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'verbose_name': 'Video Project',
                'verbose_name_plural': 'Video Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
