# Generated by Django 5.1.4 on 2025-07-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experiencehighlight_skillcategory_tool_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('about_text_1', models.TextField()),
                ('about_text_2', models.TextField(blank=True)),
                ('about_text_3', models.TextField(blank=True)),
                ('years_experience', models.CharField(default='4+', max_length=10)),
                ('projects_completed', models.CharField(default='65+', max_length=10)),
                ('happy_clients', models.CharField(default='25+', max_length=10)),
                ('coffee_consumed', models.CharField(default='∞', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='core.aboutsection')),
            ],
        ),
    ]
