# Generated by Django 5.2.4 on 2025-07-17 19:34

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(help_text='Upload video file (MP4, WebM, or OGG format)', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='videos/'),
        ),
    ]
