# Generated by Django 5.2.4 on 2025-07-17 22:35

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_videoproject_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload thumbnail image (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video_file',
            field=cloudinary.models.CloudinaryField(help_text='Upload video file (mp4, mov, avi, mkv)', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
